import os
import glob

netlist_dir = '/home/lary/simulation/BVU025/BVU025A/sim_Bias_cosim_A1/ams/config/netlist'
os.chdir(netlist_dir)

vams_content = """// AMS netlist generated by the AMS Unified netlister
// IC subversion:  IC6.1.8-64b.500.36 
// Xcelium version: 24.09-s013
// Design library name: BVU025_Lary
// Design cell name: sim_Bias_cosim_A1
// Design view name: config
// Solver: Spectre

`include "disciplines.vams"
`include "userDisciplines.vams"

// HDL file - BVU025_Lary, Buffer_DIG, functional.
// HDL file - BVU025_Lary, vaSAR6b, veriloga.
// HDL file - BVU025_Lary, vaVDAC6b_FIXED, veriloga.

`timescale 1ns / 1ns 

`worklib BVU025_Lary
`view schematic_SAR

(* cds_ams_schematic *) 
(* dfII_lib="BVU025_Lary", dfII_cell="sim_Bias_cosim_A1", dfII_view="schematic_SAR", worklib_name="BVU025_Lary", view_name="schematic_SAR" *)

module sim_Bias_cosim_A1 ();

wire [5:0] NvTrmIref;
electrical aTrimRef_5, aTrimRef_4, aTrimRef_3, aTrimRef_2, aTrimRef_1, aTrimRef_0;
electrical aVdd, aVss, SUB, TMIRefOn, TMIRefMeas, TMIRefOni, TMIRefMeasi;
electrical CLK, POR, DVDD_Trm, dIRefTMO, IREF_TrmCode, dDone, net3, net4, net5, net6, net7, VBNC, xIRefTMIO, xIRefTMIO1, xIRefTMIO2;

analog begin
    V(aVss) <+ 0.0;
    V(SUB) <+ 0.0;
    
    // Supplies and control pulses
    V(aVdd, aVss) <+ transition(($abstime < 5e-06 ? 0.0 : 3.3), 5e-06, 5e-06, 5e-06);
    V(DVDD_Trm, aVss) <+ transition(($abstime < 400e-06 ? 0.0 : 3.3), 0, 1e-09, 1e-09);
    V(POR, aVss) <+ transition(($abstime < 400e-06 ? 0.0 : (($abstime < 1.4e-03) ? 3.3 : 0.0)), 0, 1e-09, 1e-09);
    V(TMIRefOn, aVss) <+ transition(($abstime < 390e-06 ? 0.0 : (($abstime < 1.4e-03) ? 3.3 : 0.0)), 0, 1e-09, 1e-09);
    V(TMIRefOni, TMIRefOn) <+ 0.0;
    V(TMIRefMeas, aVss) <+ transition(($abstime < 1.41e-03 ? 0.0 : 3.3), 0, 1e-09, 1e-09);
    V(TMIRefMeasi, TMIRefMeas) <+ 0.0;
    
    // SAR Clock gating signals
    V(net5, aVss) <+ transition(($abstime < 400e-06 ? 0.0 : (($abstime < 1.2e-03) ? 3.3 : 0.0)), 0, 1e-09, 1e-09);
    V(net6, aVss) <+ transition(($abstime < 400e-06 ? 0.0 : ((($abstime - 400e-06) - floor(($abstime - 400e-06)/100e-06)*100e-06 < 50e-06) ? 3.3 : 0.0)), 0, 1e-09, 1e-09);
    
    // V_ISARCtl (net4) & V_IMeasCtl (net7)
    V(net4, aVss) <+ transition(($abstime < 399e-06 ? 0.0 : (($abstime <= 1.2e-03) ? 3.3 : 0.0)), 0, 1e-06, 1e-06);
    V(net7, aVss) <+ transition(($abstime < 1.40e-03 ? 0.0 : (($abstime <= 1.8e-03) ? 3.3 : 0.0)), 0, 1e-06, 1e-06);
    
    // External current source I_ISARC (2uA) during SAR (400us - 1.2ms)
    if ($abstime >= 400e-06 && $abstime <= 1.2e-03)
        I(aVdd, xIRefTMIO1) <+ 2.0e-6;
    else
        I(aVdd, xIRefTMIO1) <+ 0.0;
    
    // Switch W0 (controlled by net4 between xIRefTMIO and xIRefTMIO1)
    I(xIRefTMIO1, xIRefTMIO) <+ V(xIRefTMIO1, xIRefTMIO) / (V(net4, aVss) > 1.65 ? 1e-3 : 1e9);

    // Switch W1 (controlled by net7 between xIRefTMIO and xIRefTMIO2)
    I(xIRefTMIO, xIRefTMIO2) <+ V(xIRefTMIO, xIRefTMIO2) / (V(net7, aVss) > 1.65 ? 1e-3 : 1e9);

    // External 0V current meter V_IMeas (connected to xIRefTMIO2)
    V(xIRefTMIO2, aVss) <+ 0.0;
    
    // D2A Coupling buffer
    V(aTrimRef_5, aVss) <+ transition((NvTrmIref[5] == 1'b1 ? 3.3 : 0.0), 0, 1e-09, 1e-09);
    V(aTrimRef_4, aVss) <+ transition((NvTrmIref[4] == 1'b1 ? 3.3 : 0.0), 0, 1e-09, 1e-09);
    V(aTrimRef_3, aVss) <+ transition((NvTrmIref[3] == 1'b1 ? 3.3 : 0.0), 0, 1e-09, 1e-09);
    V(aTrimRef_2, aVss) <+ transition((NvTrmIref[2] == 1'b1 ? 3.3 : 0.0), 0, 1e-09, 1e-09);
    V(aTrimRef_1, aVss) <+ transition((NvTrmIref[1] == 1'b1 ? 3.3 : 0.0), 0, 1e-09, 1e-09);
    V(aTrimRef_0, aVss) <+ transition((NvTrmIref[0] == 1'b1 ? 3.3 : 0.0), 0, 1e-09, 1e-09);
end

Bias_A1 I_Bias (
    .En(aVdd),
    .IRefTMO(dIRefTMO),
    .SUB(SUB),
    .TMIRefMeas(TMIRefMeasi),
    .TMIRefOn(TMIRefOni),
    .VBNC(VBNC),
    .VBNC1(VBNC),
    .aVdd(aVdd),
    .aVss(aVss),
    .ibp_250n_0(net3),
    .rgTrim_IRef_5(aTrimRef_5),
    .rgTrim_IRef_4(aTrimRef_4),
    .rgTrim_IRef_3(aTrimRef_3),
    .rgTrim_IRef_2(aTrimRef_2),
    .rgTrim_IRef_1(aTrimRef_1),
    .rgTrim_IRef_0(aTrimRef_0),
    .xIRefTMIO(xIRefTMIO)
);

AN2x1 I_CLKCtl (
    .A(net5),
    .B(net6),
    .VDD(DVDD_Trm),
    .VSS(cds_globals.\\gnd! ),
    .Z(CLK)
);

vaVDAC6b_FIXED #( .transmission_delay_max(1e-09), .transmission_delay(1e-11) 
    , .threshold_low(0.25), .slew_rate_positive(1e+06), .slew_rate_negative(-1e+06) 
    , .threshold_high(0.75), .mode_decimal_display(1) )  I_Code ( 
    .VSS(cds_globals.\\gnd! ), .VDD(DVDD_Trm), .VO(IREF_TrmCode), 
    .DI(NvTrmIref));

vaSAR6b #( .threshold_low(0.25), .threshold_high(0.75), .comp_invert(1), .fall_time(1e-09) 
    , .rise_time(1e-09), .delay(1e-11) )  I_SAR6b ( 
    .VSS(cds_globals.\\gnd! ), .VDD(DVDD_Trm), .CODE(NvTrmIref), 
    .DONE(dDone), .EN(POR), .CLK(CLK), .CMP(dIRefTMO));

endmodule
"""

open('./netlist.vams', 'w').write(vams_content)
print("Updated netlist.vams with net7, net4, xIRefTMIO1, xIRefTMIO2!")
